// Generated by CoffeeScript 1.10.0
(function() {
  var bar_offset, bar_w, height;

  bar_w = 105;

  bar_offset = 110;

  height = 150;

  d3.json('data.json', function(error, data) {
    var bars, color, databox, enter_sd, items, menu, section_databox, section_scale, sections, svg;
    if (error) {
      console.warn(error);
    }
    svg = d3.select('svg').attr({
      width: bar_offset * (data.sections.filter(function(d) {
        return d.name !== "About";
      })).length,
      height: height
    });
    color = d3.scale.ordinal().domain(data.sections.filter(function(d) {
      return d.name !== "About";
    })).range(["#bebada", "#fb8072", "#80b1d3", "#fdb462", "#b3de69"]);
    menu = svg.append('g');
    section_scale = d3.scale.linear().domain([
      0, d3.max(data.sections, function(d) {
        return d.items.length;
      })
    ]).range([40, height]);
    sections = menu.selectAll('.section_menu').data(data.sections.filter(function(d) {
      return d.name !== "About";
    }));
    bars = sections.enter().append('g').attr({
      "class": 'section_menu',
      transform: function(d, i) {
        return "translate(" + (i * bar_offset) + ", 0)";
      }
    });
    bars.append('a').attr({
      'xlink:href': function(d) {
        return "#" + d.name;
      }
    }).append('rect').attr({
      "class": 'bar',
      width: bar_w,
      height: function(d) {
        return section_scale(d.items.length);
      },
      fill: function(d) {
        return color(d.name);
      }
    }).on('mouseover', function() {
      return d3.select(this).transition().duration(300).style({
        opacity: 0.7
      });
    }).on('mouseout', function() {
      return d3.select(this).transition().duration(300).style({
        opacity: 1
      });
    });
    bars.append('text').attr({
      'y': 20,
      'x': 4
    }).text(function(d) {
      return d.name;
    });
    data.sections.map(function(section) {
      return section.items.map(function(item) {
        return item.parent = section;
      });
    });
    databox = d3.select('#databox');
    section_databox = databox.selectAll('.section_databox').data(data.sections);
    enter_sd = section_databox.enter().append('div').attr({
      "class": 'section_databox'
    });
    enter_sd.append('a').attr({
      name: function(d) {
        return d.name;
      }
    });
    enter_sd.append('h3').style({
      background: function(d) {
        if (d.name !== "About") {
          return color(d.name);
        }
      },
      width: function(d) {
        return ((section_scale(d.items.length)) * 2) + "px";
      }
    }).text(function(d) {
      return d.name;
    });
    items = section_databox.selectAll('.item').data(function(d) {
      return d.items;
    });
    return items.enter().append('div').attr({
      "class": 'item'
    }).html(function(d) {
      if (d.parent.name === "Publications") {
        return "<div class='gray'>" + d.authors + "</div><div>" + d.name + "</div><div class='gray'>" + d.conference + "</div>";
      } else if (d.parent.name === "Education") {
        return "<div>" + d.name + "</div><div class='gray'>" + d.university + ", " + d.years + "</div>";
      } else if (d.parent.name === "Experience") {
        return "<div>" + d.name + "</div><div class='gray'>" + d.place + ", " + d.years + "</div>";
      } else if (d.parent.name === "Projects") {
        return "<div>" + d.name + "</div><div class='gray'>" + d.description + "</div>";
      } else if (d.parent.name === "About") {
        return "<div>" + d.text + "</div>";
      } else if (d.parent.name === "Skills") {
        return "<div>" + d.name + "</div><div class='gray'>" + d.list + "</div>";
      }
    });
  });

}).call(this);
